Improved is_displayed error handle
kaliiiiiiiiii/Selenium-Driverless pull request #201
Opened 2024-04-11 23:30 UTC by boludoz

2024-04-11 23:31 UTC, boludoz commented
The code will fail if you cannot handle that error, I recommend returning false.

2024-04-12 02:56 UTC, boludoz commented
@kaliiiiiiiiii Improved error handling a bit, since that could be the cause of the error.

2024-04-12 03:01 UTC, boludoz commented
![image](https://github.com/kaliiiiiiiiii/Selenium-Driverless/assets/11653030/1e058cd1-0dac-4c58-981f-e3936cdebb59)
On the rebound I have solved a bug in click, since in reality the error has a dot at the end, using 'in' is already solved.

2024-04-12 07:11 UTC, kaliiiiiiiiii commented
> ![image](https://private-user-images.githubusercontent.com/11653030/321841553-1e058cd1-0dac-4c58-981f-e3936cdebb59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDU5OTMsIm5iZiI6MTcxMjkwNTY5MywicGF0aCI6Ii8xMTY1MzAzMC8zMjE4NDE1NTMtMWUwNThjZDEtMGRhYy00YzU4LTk4MWYtZTM5MzZjZGViYjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDA3MDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMGFhZDU0NDY1YjY4YjA3YTBhMjlkYjY1N2NmMjBjZmQ0ZGU5OTEyZDg5OTJiODA4MzFhMjUwNjQ0ZDJkYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7vzlHjgouqcd305qDLb-zkffpbP4-LKXmzVaFMtXwR0) I also improved the others a little using in.

@boludoz Can you provide an example where that would make a difference?

2024-04-12 07:15 UTC, kaliiiiiiiiii requested changes

2024-04-12 07:15 UTC, kaliiiiiiiiii commented on src/selenium_driverless/types/webelement.py
> +                return False
Should raise an exception in my view.
Returning `False` just isn't something a user would expect, I suppose

2024-04-12 07:16 UTC, kaliiiiiiiiii commented
> The code will fail if you cannot handle that error, I recommend returning false.

@boludoz 
Should raise an exception in my view.
Returning `False` just isn't something a user would expect, I suppose

2024-04-13 18:24 UTC, kaliiiiiiiiii approved these changes
nvm you're right😂

2024-04-13 18:27 UTC, kaliiiiiiiiii approved these changes

2024-04-13 18:28 UTC, merged